name: Go

on:
  push:
    branches: ["master"]
    paths:
      - "**.go"
      - "**.yaml"
      - "**.yml"
      - "**.json"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: ["master"]
    paths:
      - "**.go"
      - "**.yaml"
      - "**.yml"
      - "**.json"
      - "go.mod"
      - "go.sum"

concurrency:
  # prevent multiple workflows from running at the same time for the same pr/branch/tag etc.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          # Latest 'stable' go version. Use 'oldstable'
          # in order to use the previous old stable version.
          go-version: "stable"

      - name: Build go snippets in readme
        run: |
          mkdir -p ~/.local/bin/
          wget -O ~/.local/bin/lintdown.sh https://raw.githubusercontent.com/ChillerDragon/lintdown.sh/master/lintdown.sh
          chmod +x ~/.local/bin/lintdown.sh
          lintdown.sh README.md

      - name: Build
        run: go build -v ./...

      - name: Test
        # limit parallelization in order to avoid potentially weird github runner behavior.
        run: go test -timeout 900s -race -count=1 -parallel 2 ./...

      - name: Format
        run: diff -u <(echo -n) <(gofmt -d ./)
